//@MovieTracker.API_HostAddress = https://localhost:7104
@Host = https://localhost:7104
###
  
GET {{Host}}/api/movies/get/76
Accept: application/json

###

GET {{Host}}/api/movies/search?name=inception
Accept: application/json
###

GET {{Host}}/api/movies/get/{Id}

###

GET {{Host}}/api/movies/search?name=no strings attached

###
